-- AlterTable
ALTER TABLE "Post" ADD COLUMN "fundingGoal" DOUBLE PRECISION DEFAULT 100.0;
ALTER TABLE "Post" ADD COLUMN "fundUSDC" DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE "Post" ADD COLUMN "fundCount" INTEGER DEFAULT 0;
